# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 637560f2eeefb0251786d4180748bcbbccc7e9a9c6128925ce280804ffd7e7a8dc45a3e82b24c1d79817ae83028fd22c7852a13d8b62bc3a137d36e4377139fd

test:
  secret_key_base: 9fa4f1fed047409497678de2b40d0d7b1bde6748cc6ee571382c90c8e19170d371312c76c8981174f5ce006158d1a5c761d139627178d173b0009b212595e4d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
